# Site settings
title: めもなど
description: "作業めも等。日記、雑記、その他何でも"
url: "http://tayu.github.io"

## サイト出力先
destination: ../../tayu.github.io
## ベース URL
baseurl: "."
## パーマリンクスタイル
permalink: pretty

# select syntax highlight engine
highlighter: pygments
# select Markdown engine
markdown: kramdown

# Kramdown options
kramdown:
  input			: GFM
  hard_wrap		: false
  auto_ids		: true
  entity_output		: as_char
  toc_levels		: 1..2
  parse_block_html	: true


# ToDo
#   bash のシンタックスハイライトが効かない
#     yaml や java 等は効く。一覧のページ(http://pygments.org/languages/) の
#     Other markup だから？ Demo ページでは変換できるのだが
#     redcarpe だと bash は認識する。が、インデントがおかしくなるし、
#     目次ができない
#       2017/03/01

