# Site settings
title: 言語めも
description: "プログラミング言語の超入門。または自分の学習の足跡として"

## 出力先
destination: ../main/lang
## ベース URL
permalink: pretty
baseurl: "."
# Markdown レンダラ
highlighter: pygments
## マークダウン
kramdown:
  input: GFM
  hard_wrap: false

